import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class SurveyAnalyticsCreate {
  @ApiProperty()
  survey_id: string;
  @ApiProperty()
  total_responsess: number;
  @ApiProperty()
  average_score: string;
}

export class SurveyAnalytics {
  @ApiProperty()
  id: number;
  @ApiProperty()
  survey_id: string;
  @ApiProperty()
  total_responsess: number;
  @ApiProperty()
  average_score: string;
  @ApiProperty()
  created_at: Date;
  @ApiProperty()
  updated_at: Date;
}
