/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { Respondent, RespondentCreate } from './dtos/Respondent.dto';
import { RespondentController } from './Respondent.controller';
import { RespondentService } from './Respondent.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('RespondentController', () => {
  let controller: RespondentController;
  let spyService: RespondentService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: RespondentService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [RespondentController],
      providers: [RespondentService, ApiServiceProvider],
    }).compile();

    controller = module.get<RespondentController>(RespondentController);
    spyService = module.get<RespondentService>(RespondentService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call RespondentController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call RespondentController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new Respondent();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
