/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Respondent } from './Respondent.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { RespondentService } from './Respondent.service';
import { RespondentController } from './Respondent.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Respondent])],
  providers: [RespondentService],
  exports: [RespondentService],
  controllers: [RespondentController],
})
export class RespondentModule {}
