import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class ResponseCreate {
  @ApiProperty()
  question_id: string;
  @ApiProperty()
  response_value: string;
  @ApiProperty()
  respondent_id: string;
}

export class Response {
  @ApiProperty()
  id: number;
  @ApiProperty()
  question_id: string;
  @ApiProperty()
  response_value: string;
  @ApiProperty()
  respondent_id: string;
  @ApiProperty()
  created_at: Date;
  @ApiProperty()
  updated_at: Date;
}
