/**
 * This file generated by Apso.
 */
import { SurveyModule } from './Survey/Survey.module';
import { QuestionModule } from './Question/Question.module';
import { ResponseModule } from './Response/Response.module';
import { RespondentModule } from './Respondent/Respondent.module';
import { SurveyAnalyticsModule } from './SurveyAnalytics/SurveyAnalytics.module';

export default [
  SurveyModule,
  QuestionModule,
  ResponseModule,
  RespondentModule,
  SurveyAnalyticsModule,
];
