import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class QuestionCreate {
  @ApiProperty()
  survey_id: string;
  @ApiProperty()
  question_text: string;
  @ApiProperty()
  response_type: string;
}

export class Question {
  @ApiProperty()
  id: number;
  @ApiProperty()
  survey_id: string;
  @ApiProperty()
  question_text: string;
  @ApiProperty()
  response_type: string;
  @ApiProperty()
  created_at: Date;
  @ApiProperty()
  updated_at: Date;
}
