import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class RespondentCreate {
  @ApiProperty()
  name: string;
  @ApiProperty()
  email: string;
}

export class Respondent {
  @ApiProperty()
  id: number;
  @ApiProperty()
  name: string;
  @ApiProperty()
  email: string;
  @ApiProperty()
  created_at: Date;
  @ApiProperty()
  updated_at: Date;
}
