/**
 * This file generated by Apso.
 */
import { Controller } from '@nestjs/common';
import {
  Crud,
  CrudController,
  Override,
  ParsedRequest,
  CrudRequest,
  ParsedBody,
  CreateManyDto,
} from '@nestjsx/crud';
import { ApiTags, ApiResponse, ApiOperation, ApiBody } from '@nestjs/swagger';
import {
  SurveyAnalytics,
  SurveyAnalyticsCreate,
} from './dtos/SurveyAnalytics.dto';
import { SurveyAnalyticsService } from './SurveyAnalytics.service';

@Crud({
  model: {
    type: SurveyAnalytics,
  },
  dto: {
    create: SurveyAnalyticsCreate,
    update: SurveyAnalytics,
    replace: SurveyAnalytics,
  },
  query: {
    /**
     * commenting out limit and pagination because of an issue with Crud lib: https://github.com/nestjsx/crud/issues/777
     */
    // TODO: make limit env driven?
    limit: 5,
    alwaysPaginate: true,
  },
})
@Controller('SurveyAnalyticss')
@ApiTags('SurveyAnalyticss')
export class SurveyAnalyticsController
  implements CrudController<SurveyAnalytics>
{
  constructor(public service: SurveyAnalyticsService) {}

  get base(): CrudController<SurveyAnalytics> {
    return this;
  }

  @Override('getManyBase')
  @ApiOperation({ summary: 'Retrieve multiple SurveyAnalyticss' })
  getMany(@ParsedRequest() req: CrudRequest) {
    return this.base.getManyBase(req);
  }

  @Override('getOneBase')
  @ApiOperation({ summary: 'Retrieve a single SurveyAnalytics' })
  get(@ParsedRequest() req: CrudRequest) {
    return this.base.getOneBase(req);
  }

  @Override('createOneBase')
  @ApiOperation({ summary: 'Create a single SurveyAnalytics' })
  @ApiBody({
    type: SurveyAnalyticsCreate,
    description:
      'The Description for the Post Body. Please look into the DTO. You will see the @ApiOptionalProperty used to define the Schema.',
  })
  create(
    @ParsedRequest() req: CrudRequest,
    @ParsedBody() dto: SurveyAnalytics,
  ) {
    return this.base.createOneBase(req, dto);
  }

  @Override('createManyBase')
  @ApiOperation({ summary: 'Create multipleSurveyAnalyticss' })
  createMany(
    @ParsedRequest() req: CrudRequest,
    @ParsedBody() dto: CreateManyDto<SurveyAnalytics>,
  ) {
    return this.base.createManyBase(req, dto);
  }

  @Override('updateOneBase')
  @ApiOperation({ summary: 'Update a single SurveyAnalytics' })
  update(
    @ParsedRequest() req: CrudRequest,
    @ParsedBody() dto: SurveyAnalytics,
  ) {
    return this.base.updateOneBase(req, dto);
  }

  @Override('replaceOneBase')
  @ApiOperation({ summary: 'Replace a single SurveyAnalytics' })
  replace(
    @ParsedRequest() req: CrudRequest,
    @ParsedBody() dto: SurveyAnalytics,
  ) {
    return this.base.replaceOneBase(req, dto);
  }

  @Override('deleteOneBase')
  @ApiOperation({ summary: 'Delete a single SurveyAnalytics' })
  delete(@ParsedRequest() req: CrudRequest) {
    return this.base.deleteOneBase(req);
  }
}
