/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import {
  SurveyAnalytics,
  SurveyAnalyticsCreate,
} from './dtos/SurveyAnalytics.dto';
import { SurveyAnalyticsController } from './SurveyAnalytics.controller';
import { SurveyAnalyticsService } from './SurveyAnalytics.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('SurveyAnalyticsController', () => {
  let controller: SurveyAnalyticsController;
  let spyService: SurveyAnalyticsService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: SurveyAnalyticsService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [SurveyAnalyticsController],
      providers: [SurveyAnalyticsService, ApiServiceProvider],
    }).compile();

    controller = module.get<SurveyAnalyticsController>(
      SurveyAnalyticsController,
    );
    spyService = module.get<SurveyAnalyticsService>(SurveyAnalyticsService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call SurveyAnalyticsController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call SurveyAnalyticsController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new SurveyAnalytics();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
