/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { SurveyAnalytics } from './SurveyAnalytics.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { SurveyAnalyticsService } from './SurveyAnalytics.service';
import { SurveyAnalyticsController } from './SurveyAnalytics.controller';

@Module({
  imports: [TypeOrmModule.forFeature([SurveyAnalytics])],
  providers: [SurveyAnalyticsService],
  exports: [SurveyAnalyticsService],
  controllers: [SurveyAnalyticsController],
})
export class SurveyAnalyticsModule {}
